version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=em-postgres
      - POSTGRES_DB=em-backend-local
    ports:
      - '5432:5432'
    restart: always
