version: '3.8'

services:
  postgres-test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local
    ports:
      - '5433:5433'
    restart: always
