version: '3.8'

services:
  postgres-development:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=em_persistance
    ports:
      - '5432:5432'
    restart: always
