name: Deployment Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  cancel-previous:
    runs-on: ubuntu-22.04
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  npm-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  lint:
    needs: npm-ci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  build:
    needs: npm-ci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Unusued beacuse render makes the build again
      # - name: Upload build
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Unusued beacuse render makes the build again
      # - name: Download build
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dist
      #     path: dist

      - name: Execute tests
        run: npm test

  # before-deploy:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Lint code
  #       run: npm run lint

  #     - name: Build
  #       run: npm run build

  #     - name: Set up Test DB
  #       run: npm run docker:up:test

  #     - name: Execute tests
  #       run: npm run test
