name: Deployment Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  test:
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm run test

  # before-deploy:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Lint code
  #       run: npm run lint

  #     - name: Build
  #       run: npm run build

  #     - name: Set up Test DB
  #       run: npm run docker:up:test

  #     - name: Execute tests
  #       run: npm run test
