name: Deployment Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  before-deploy:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Set up Test DB
        run: npm run docker:up:test

      - name: Execute tests
        run: npm run test
