name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --no-audit --no-found --no-optional

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
